POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "Gilvan Nunes",
    "username": "gilvan.nunes",
    "email": "gilvan.nunes@hotmail.com",
    "password": "marazul10"
}